window.SEED_EVIDENCE = [
  {
    id: "E-001",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/373711674/how-do-i-use-classic-search-instead-of-ai?hl=en",
    date: "2025-09-17",
    text: "A remembered yellow sticky note and a tattoo-on-arm photo no longer appear for the same descriptive searches.",
    scope: "in_scope",
    mediaType: "Mixed photos",
    remembered: ["visual appearance", "object", "body location"],
    forgotten: ["date", "exact text", "album"],
    queryBehavior: "Descriptive object and attribute keywords",
    failureMode: "vocabulary_mismatch",
    opportunity: "Descriptive cue translation",
    workaround: "Switch to another gallery app",
    outcome: "unresolved",
    effort: 4,
    severity: 5,
    abandoned: true,
    confidence: 0.96,
    relevanceReason: "The user remembers visual attributes but lacks metadata and exact searchable wording."
  },
  {
    id: "E-002",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/1fa4fg1/what_happened_to_the_search_feature_on_the_app/",
    date: "2024-09-06",
    text: "Searching for a bike used to return relevant photos and screenshots, but the same broad cue stopped working.",
    scope: "in_scope",
    mediaType: "Photos and screenshots",
    remembered: ["object"],
    forgotten: ["date", "source", "exact scene"],
    queryBehavior: "Single broad object keyword",
    failureMode: "inconsistent_results",
    opportunity: "Descriptive cue translation",
    workaround: "Repeated keyword attempts",
    outcome: "unresolved",
    effort: 3,
    severity: 4,
    abandoned: false,
    confidence: 0.91,
    relevanceReason: "The only reliable memory cue is a broad object shared across media types."
  },
  {
    id: "E-003",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/1lnvqt2/everything_wrong_with_google_photos/",
    date: "2025-06-29",
    text: "The user first finds a related photo, checks its date, then searches that date and hopes the target appears.",
    scope: "in_scope",
    mediaType: "Photos",
    remembered: ["related photo", "approximate event"],
    forgotten: ["exact date", "searchable subject"],
    queryBehavior: "Anchor-photo lookup followed by date search",
    failureMode: "metadata_uncertainty",
    opportunity: "Anchor-based retrieval",
    workaround: "Use another photo as a temporal anchor",
    outcome: "partial",
    effort: 5,
    severity: 4,
    abandoned: false,
    confidence: 0.95,
    relevanceReason: "The workaround reveals associative memory: a nearby known item is easier to recall than the target."
  },
  {
    id: "E-004",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/286489095/how-do-i-get-google-photo-to-show-all-my-photos-chronologically-begining-with-the-most-recent-ones?hl=en",
    date: "2024-07-21",
    text: "A search for today's date returned unrelated photos from nearly ten years earlier.",
    scope: "in_scope",
    mediaType: "Photos",
    remembered: ["exact day", "recent capture"],
    forgotten: ["filename"],
    queryBehavior: "Date query",
    failureMode: "wrong_metadata_match",
    opportunity: "Temporal uncertainty recovery",
    workaround: "Browse chronologically",
    outcome: "unresolved",
    effort: 3,
    severity: 3,
    abandoned: false,
    confidence: 0.92,
    relevanceReason: "Even a strong remembered cue can fail when returned metadata conflicts with user memory."
  },
  {
    id: "E-005",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/308953776/i-can%E2%80%99t-search-my-photos-up-like-i-used-to-before-google-photos-was-the-easiest-what-happened-jus?hl=en",
    date: "2024-11-20",
    text: "Even a basic remembered subject returns no result, leaving the user without a way to reformulate.",
    scope: "in_scope",
    mediaType: "Unspecified photo",
    remembered: ["basic subject"],
    forgotten: ["date", "location", "exact labels"],
    queryBehavior: "Basic subject keyword",
    failureMode: "no_recovery_path",
    opportunity: "Query repair and cue elicitation",
    workaround: "Try increasingly specific terms",
    outcome: "unresolved",
    effort: 4,
    severity: 4,
    abandoned: true,
    confidence: 0.82,
    relevanceReason: "The initial cue is weak and the interface provides no structured path to add another clue."
  },
  {
    id: "E-006",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/312881310/can-t-find-by-date-anymore?hl=en",
    date: "2024-12-12",
    text: "A remembered calendar day now returns one item, sometimes from a different date, instead of all matching years.",
    scope: "in_scope",
    mediaType: "Photos and videos",
    remembered: ["day and month"],
    forgotten: ["year", "event details"],
    queryBehavior: "Recurring-date query",
    failureMode: "query_interpretation",
    opportunity: "Temporal uncertainty recovery",
    workaround: "Remove quotation marks and inspect more results",
    outcome: "partial",
    effort: 4,
    severity: 3,
    abandoned: false,
    confidence: 0.94,
    relevanceReason: "The user remembers a recurring date pattern but not the year; the system assumes a narrower intent."
  },
  {
    id: "E-007",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/17yjf54",
    date: "2023-11-18",
    text: "Multiple date formats failed; another user later saw only seven of roughly thirty photos from the remembered day.",
    scope: "in_scope",
    mediaType: "Photos",
    remembered: ["exact or approximate date"],
    forgotten: ["filename", "album"],
    queryBehavior: "Repeated date-format reformulation",
    failureMode: "inconsistent_results",
    opportunity: "Temporal uncertainty recovery",
    workaround: "Try many date formats or switch device",
    outcome: "partial",
    effort: 5,
    severity: 4,
    abandoned: false,
    confidence: 0.93,
    relevanceReason: "The same cue produces incomplete results across interfaces, increasing uncertainty and effort."
  },
  {
    id: "E-008",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/1ijy6ie",
    date: "2025-02-07",
    text: "Recognizable words in slides, documents, and photos stopped retrieving some images until users learned to add quotes.",
    scope: "in_scope",
    mediaType: "Screenshots and documents",
    remembered: ["visible text", "document type"],
    forgotten: ["date", "source app", "filename"],
    queryBehavior: "OCR text keyword",
    failureMode: "hidden_query_syntax",
    opportunity: "Screenshot and document cue recovery",
    workaround: "Put remembered text inside quotation marks",
    outcome: "success_after_help",
    effort: 4,
    severity: 4,
    abandoned: false,
    confidence: 0.97,
    relevanceReason: "The cue exists inside the image, but retrieval depends on an undiscoverable query convention."
  },
  {
    id: "E-009",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/1px47il/googleif_youre_listening_your_photos_app_is_a/",
    date: "2025-12-27",
    text: "Broad searches retrieve only a fraction of remembered dog or BBQ photos, forcing date recall and timeline scrolling.",
    scope: "in_scope",
    mediaType: "Photos",
    remembered: ["person or pet", "activity", "object"],
    forgotten: ["date", "exact scene"],
    queryBehavior: "Broad semantic search followed by manual scrolling",
    failureMode: "incomplete_result_set",
    opportunity: "Result-set completeness and refinement",
    workaround: "Remember the date and scroll the timeline",
    outcome: "partial",
    effort: 5,
    severity: 5,
    abandoned: false,
    confidence: 0.96,
    relevanceReason: "The correct category is known, but poor recall of time makes manual recovery expensive."
  },
  {
    id: "E-010",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/1lklsk2/classic_search_is_gone/",
    date: "2025-06-26",
    text: "A parent remembers a daughter singing Toto but the conversational query fails to surface the childhood photo.",
    scope: "in_scope",
    mediaType: "Photo or video",
    remembered: ["person", "life stage", "activity", "song context"],
    forgotten: ["date", "exact file type", "filename"],
    queryBehavior: "Natural-language episodic description",
    failureMode: "episodic_cue_mismatch",
    opportunity: "Episodic clue composition",
    workaround: "Try renamed keywords and alternate search modes",
    outcome: "unresolved",
    effort: 5,
    severity: 5,
    abandoned: true,
    confidence: 0.94,
    relevanceReason: "Several strong autobiographical cues exist, but they do not map cleanly to indexed visual labels."
  },
  {
    id: "E-011",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/269885700/i-want-to-mark-who-is-in-a-picture?hl=en",
    date: "2024-04-17",
    text: "The same person appears in additional photos, but face grouping misses them and correction can be laborious.",
    scope: "in_scope",
    mediaType: "People photos",
    remembered: ["person identity"],
    forgotten: ["date", "event", "location"],
    queryBehavior: "Person search and face-group browsing",
    failureMode: "entity_recognition_gap",
    opportunity: "Person-identity recovery",
    workaround: "Create a manual album or correct faces individually",
    outcome: "partial",
    effort: 5,
    severity: 3,
    abandoned: false,
    confidence: 0.89,
    relevanceReason: "A remembered person is the primary cue, but the entity index is incomplete."
  },
  {
    id: "E-012",
    source: "Wired field test",
    sourceType: "Editorial test",
    url: "https://www.wired.com/story/google-photos-ask-photos-gemini/",
    date: "2024-09-05",
    text: "A relationship-based query succeeded, but another travel query improved only after being run again.",
    scope: "in_scope",
    mediaType: "People and travel photos",
    remembered: ["relationship", "event", "trip", "relative time"],
    forgotten: ["exact date", "place detail"],
    queryBehavior: "Conversational multi-clue search and retry",
    failureMode: "non_deterministic_results",
    opportunity: "Episodic clue composition",
    workaround: "Repeat the same query",
    outcome: "success_after_retry",
    effort: 2,
    severity: 2,
    abandoned: false,
    confidence: 0.88,
    relevanceReason: "The test shows both the promise and inconsistency of combining incomplete episodic cues."
  },
  {
    id: "E-013",
    source: "TechRadar field test",
    sourceType: "Editorial test",
    url: "https://www.techradar.com/ai-platforms-assistants/gemini/forget-the-robots-this-is-the-reason-ai-is-the-best-thing-to-happen-since-smartphone-cameras",
    date: "2025-11-28",
    text: "A user with 172,000 photos found an old bay-window image using remembered object and appearance cues.",
    scope: "in_scope",
    mediaType: "Home photo",
    remembered: ["object", "visual appearance", "purpose"],
    forgotten: ["date", "device", "album"],
    queryBehavior: "Natural-language object and attribute query",
    failureMode: "counterevidence_success",
    opportunity: "Descriptive cue translation",
    workaround: "Conversational search instead of scrolling",
    outcome: "success",
    effort: 1,
    severity: 1,
    abandoned: false,
    confidence: 0.9,
    relevanceReason: "A successful case acts as counterevidence and shows which descriptive cues can work."
  },
  {
    id: "E-014",
    source: "The Verge",
    sourceType: "Editorial test",
    url: "https://www.theverge.com/how-to/758206/bring-back-google-photos-classic-search-instead-of-gemini",
    date: "2025-08-12",
    text: "The tester repeatedly switched back because AI search felt slower, less helpful, and more confusing than classic search.",
    scope: "adjacent",
    mediaType: "Mixed library",
    remembered: ["known search target"],
    forgotten: ["unspecified"],
    queryBehavior: "Switch between AI and classic search",
    failureMode: "interaction_cost",
    opportunity: "Query repair and cue elicitation",
    workaround: "Disable AI search in settings",
    outcome: "success_via_alternative",
    effort: 3,
    severity: 3,
    abandoned: false,
    confidence: 0.78,
    relevanceReason: "Relevant to the retrieval journey, but the memory state is not described clearly enough for core evidence."
  },
  {
    id: "E-015",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/88651366/is-there-a-reliable-way-to-do-a-text-search-in-a-photo-description?hl=en",
    date: "2020-12-14",
    text: "A user asks for reliable description search when common words create ambiguity and inconsistent matching.",
    scope: "in_scope",
    mediaType: "Photos with descriptions",
    remembered: ["description phrase"],
    forgotten: ["date", "file location"],
    queryBehavior: "Description text search",
    failureMode: "ambiguous_language",
    opportunity: "Descriptive cue translation",
    workaround: "Try less redundant terms",
    outcome: "partial",
    effort: 3,
    severity: 3,
    abandoned: false,
    confidence: 0.86,
    relevanceReason: "Natural memory language does not map reliably to indexed or manually entered descriptions."
  },
  {
    id: "E-016",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/318370488/can-t-find-my-photos-from-2016?hl=en",
    date: "2025-01-13",
    text: "Photos from 2016 appear absent, including important childhood memories.",
    scope: "out_of_scope",
    mediaType: "Photos",
    remembered: ["year", "people", "life period"],
    forgotten: ["backup state"],
    queryBehavior: "Search and restoration request",
    failureMode: "missing_or_not_backed_up",
    opportunity: "Excluded: availability and backup",
    workaround: "Check trash, backup, and recently added",
    outcome: "unresolved",
    effort: 4,
    severity: 5,
    abandoned: false,
    confidence: 0.98,
    relevanceReason: "The evidence concerns availability or backup rather than incomplete-memory retrieval."
  },
  {
    id: "E-017",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/369464340/missing-years-of-photos-i-didn-t-delete?hl=en",
    date: "2025-08-31",
    text: "Several years of photos appear missing despite the user believing they were not deleted.",
    scope: "out_of_scope",
    mediaType: "Photos",
    remembered: ["missing year range"],
    forgotten: ["account", "backup state"],
    queryBehavior: "Recovery request",
    failureMode: "missing_or_deleted",
    opportunity: "Excluded: availability and backup",
    workaround: "Check accounts and backup settings",
    outcome: "unresolved",
    effort: 5,
    severity: 5,
    abandoned: false,
    confidence: 0.99,
    relevanceReason: "This is a loss or account-state issue, not a cue-based search breakdown."
  },
  {
    id: "E-018",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/19bjybr/how_can_i_recover_permanently_deleted_photos_both/",
    date: "2024-01-20",
    text: "The user permanently deleted cloud photos while managing storage and asks how to recover them.",
    scope: "out_of_scope",
    mediaType: "Photos and videos",
    remembered: ["deleted collection"],
    forgotten: ["deletion consequences"],
    queryBehavior: "Recovery request",
    failureMode: "user_deleted_content",
    opportunity: "Excluded: availability and backup",
    workaround: "Look for recovery options",
    outcome: "unresolved",
    effort: 5,
    severity: 5,
    abandoned: false,
    confidence: 1,
    relevanceReason: "The content is no longer available; search cue quality is not the cause."
  },
  {
    id: "E-019",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/jh9w7w/what_the_hell_is_up_with_google_photos_being/",
    date: "2020-10-25",
    text: "The interface loads too slowly to drill into photos.",
    scope: "adjacent",
    mediaType: "Photos",
    remembered: ["unspecified target"],
    forgotten: ["unspecified"],
    queryBehavior: "Browse and drill down",
    failureMode: "system_latency",
    opportunity: "Excluded: general performance",
    workaround: "Clear cache and retry",
    outcome: "unresolved",
    effort: 4,
    severity: 3,
    abandoned: true,
    confidence: 0.97,
    relevanceReason: "Latency affects retrieval effort, but no incomplete-memory episode is described."
  },
  {
    id: "E-020",
    source: "Google Photos Community",
    sourceType: "Support forum",
    url: "https://support.google.com/photos/thread/153355203/how-can-i-search-for-photos-by-text-in-the-photo?hl=en",
    date: "2022-03-03",
    text: "The user asks how to retrieve a photo using remembered text visible inside it.",
    scope: "in_scope",
    mediaType: "Screenshot or text photo",
    remembered: ["visible text"],
    forgotten: ["date", "media type", "folder"],
    queryBehavior: "OCR text search",
    failureMode: "capability_discoverability",
    opportunity: "Screenshot and document cue recovery",
    workaround: "Learn that visible text can be searched",
    outcome: "success_after_help",
    effort: 2,
    severity: 2,
    abandoned: false,
    confidence: 0.9,
    relevanceReason: "The memory cue is strong, but the user does not know whether or how the system supports it."
  },
  {
    id: "E-021",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/1796l2z",
    date: "2023-10-16",
    text: "Two thousand trip photos were inconsistently visible across timeline, filename, person search, web, and mobile.",
    scope: "in_scope",
    mediaType: "Travel photos",
    remembered: ["trip", "person", "filename", "approximate date"],
    forgotten: ["processing status", "exact timeline position"],
    queryBehavior: "Cross-interface and multi-cue troubleshooting",
    failureMode: "cross_surface_inconsistency",
    opportunity: "Cross-surface retrieval confidence",
    workaround: "Switch browser, device, and cue type",
    outcome: "success_after_delay",
    effort: 5,
    severity: 3,
    abandoned: false,
    confidence: 0.88,
    relevanceReason: "The target exists, but inconsistent surfaces make the user doubt where and how it can be retrieved."
  },
  {
    id: "E-022",
    source: "Reddit r/googlephotos",
    sourceType: "Reddit",
    url: "https://www.reddit.com/r/googlephotos/comments/g5c3be",
    date: "2020-04-21",
    text: "After freeing device space, backed-up photos could not be located in Google Photos.",
    scope: "out_of_scope",
    mediaType: "Photos and videos",
    remembered: ["recent deletion action"],
    forgotten: ["backup destination", "account state"],
    queryBehavior: "Manual inspection and recovery request",
    failureMode: "backup_or_sync_state",
    opportunity: "Excluded: availability and backup",
    workaround: "Verify account and cloud backup",
    outcome: "unresolved",
    effort: 5,
    severity: 5,
    abandoned: false,
    confidence: 0.99,
    relevanceReason: "The core uncertainty is whether the content was backed up, not how it is remembered."
  }
];

window.FAILURE_LABELS = {
  vocabulary_mismatch: "Vocabulary mismatch",
  inconsistent_results: "Inconsistent results",
  metadata_uncertainty: "Metadata uncertainty",
  wrong_metadata_match: "Wrong metadata match",
  no_recovery_path: "No recovery path",
  query_interpretation: "Query interpretation",
  hidden_query_syntax: "Hidden query syntax",
  incomplete_result_set: "Incomplete result set",
  episodic_cue_mismatch: "Episodic cue mismatch",
  entity_recognition_gap: "Entity recognition gap",
  non_deterministic_results: "Non-deterministic results",
  counterevidence_success: "Successful counterevidence",
  interaction_cost: "Interaction cost",
  ambiguous_language: "Ambiguous language",
  missing_or_not_backed_up: "Missing or not backed up",
  missing_or_deleted: "Missing or deleted",
  user_deleted_content: "Deleted content",
  system_latency: "System latency",
  capability_discoverability: "Capability discoverability",
  cross_surface_inconsistency: "Cross-surface inconsistency",
  backup_or_sync_state: "Backup or sync state"
};
